### ISSUE TITLE
Any issue in gaussian naive bayes model? Gssoc23 contributer here

### ISSUE THREAD

**Issue by s0oraj** [abhijeet141/CropForesight#1]
Hi @akshitagupta15june , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by abhijeet141** [comment]
Hi @s0oraj ,

Thank you for reaching out and expressing your interest in resolving an issue. I appreciate your enthusiasm and your background in machine learning.

In coming days I will be adding different issues on which you can work on and could you please provide more details about the specific issue you would like to work on? It would be helpful if you could elaborate on the problem you are interested in resolving in this project.

Thank you for your understanding, and I look forward to hearing back from you.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
