### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [abhijeet141/CropForesight#10]
I want to add readme badges .Please assign this issue to me
![badges](https://github.com/abhijeet141/CropForesight/assets/104543751/45e793d1-5ca6-4e03-9139-280519e0953a)

**Comment by abhijeet141** [comment]
Hi @S-ishita 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
