### ISSUE TITLE
🐛 [BUG] - Weather Page not responsive for mobile view and the Search Bar is not in center

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [abhijeet141/CropForesight#100]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Right now the Weather Page is not responsive for mobile view and the Search Bar should be at the center |
| **Screenshots** |

**Desktop View**
<img width="772" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/70560812/c518fc53-7bd0-474a-a401-e829dd57e2c5">
**Mobile View**
<img width="180" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/70560812/ef72290d-7dbe-4106-a143-99c182b794be">

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @Ishita-Ghosh-25 Thank you for creating the issue but this issue is already resolved.
