### ISSUE TITLE
💡 [REQUEST] - Enhance UI of the Contact us page

### ISSUE THREAD

**Issue by Pragati-3003** [abhijeet141/CropForesight#101]
- [x] I am from GSSoC'23.
- [x ] I would like to be assigned this task.
I would like to change the ui of the contact us page by adding some cool effects.
So,please assign this issue to me .
![Screenshot 2023-06-20 143726](https://github.com/abhijeet141/CropForesight/assets/132778037/b343cb00-8138-41f7-a134-f3b33bb401b5)

**Comment by abhijeet141** [comment]
Hi @Pragati-3003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
