### ISSUE TITLE
💡 [REQUEST] - <Footer Addition>

### ISSUE THREAD

**Issue by PR1YAM9** [abhijeet141/CropForesight#102]
- [ ] I am from GSSoC'23.
- [ ] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Addition of footer|
| **Solution Proposed**      |I will add footer with links to increase the navigation and flow of thee webpage|
| **Additional Context**     |I will take consideration of the theme of the webpage|
| **Screenshots**            |[made this for a freelance project<img width="952" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/92604300/d873f122-6453-47bd-a4d8-e6c0e820f8ce">]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ ] I follow the Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @PR1YAM9 
Thank you for creating the issue but this issue is already there.
