### ISSUE TITLE
💡 [REQUEST] - UI of about us page 

### ISSUE THREAD

**Issue by smritimangal26** [abhijeet141/CropForesight#105]
- [. ] I am from GSSoC'23.
- [ .] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The UI of the about us page is not attractive like the Salient Feature part, the heading is dull while the para is too bold, the heading is also not properly aligned  |
| **Solution Proposed**      |Would like to improve the about us page ,also the hover effect can be given to the image to make it look more attractive

| **Screenshots**            
![Screenshot (65)](https://github.com/abhijeet141/CropForesight/assets/129358356/bfc5b078-334c-4354-90d7-8b8dd4636171)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ .] I follow the Contributing Guidelines of this project.
- [ .] I have checked the current issues for duplicate problems.
- [ .] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @smritimangal26 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by smritimangal26** [comment]
yes ,I am on it
