### ISSUE TITLE
💡 [REQUEST] - Add preloader to the website

### ISSUE THREAD

**Issue by Prajwal0225** [abhijeet141/CropForesight#106]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | Add a preloader to the website for better user experience |
| **Solution Proposed**      | I suggest implementing a simple preloader animation that is displayed while the website content is being loaded. This will give users a visual indication that the website is still loading and prevent them from experiencing a blank or unresponsive page during the loading process. |
| **Alternative Solutions**  | |
| **Additional Context**     | Currently, when visiting the website, there is no visual indication that the content is being loaded. Users may perceive the website as slow or unresponsive during this time. By adding a preloader, we can improve the user experience and provide a more polished look and feel to the website. |
| **Screenshots**            |  |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @Prajwal0225 
Thank you for creating the issue but this feature is already implemented
