### ISSUE TITLE
💡 [REQUEST] Adding a Blogs Page to the website

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#107]
- [x] I am from GSSoC'23.
- [ ] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | I would like to add blog page to the website. |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
