### ISSUE TITLE
💡 [REQUEST] - adding the MIT License badge to the licenses section and edit the text.

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#108]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The readme file of the repo should have a Licenses badge in the Licenses section and the text of Licenses section should be edited to make it more professional. |
| **Solution Proposed**      |I can add the Licenses badge and edit text of Licenses section|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |
![afters](https://github.com/abhijeet141/CropForesight/assets/116020663/2322c5d0-72f2-4378-8ee3-c7592b9c3e0a)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @1Shubham7 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue
