### ISSUE TITLE
💡 [REQUEST] - Adding a socials section and badges to that section in the readme

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#111]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

**Concise Description**    
We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.
Please assign me this issue under GSSoC'23 |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @1Shubham7
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue

**Comment by abhijeet141** [comment]
@1Shubham7 Make the changes on the frontend repo not on this as this repo is not being evaluated
