### ISSUE TITLE
Website not responsive on mobile

### ISSUE THREAD

**Issue by avnigoyal25** [abhijeet141/CropForesight#12]
![Screenshot (107)](https://github.com/abhijeet141/CropForesight/assets/91952706/ce64b02d-dd67-4609-8f71-db5359eaa2ef)

Please assign this issue to me under GSSOC'23.

**Comment by abhijeet141** [comment]
Hi @avnigoyal25 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by avnigoyal25** [comment]
Thankyou so much!!
