### ISSUE TITLE
Template for people to have a proper format for bug fix, pull requests, new feature addition etc. 

### ISSUE THREAD

**Issue by tuhinaww** [abhijeet141/CropForesight#13]
| Field | Value                           |
|-------|---------------------------------|
| About | Template for people to have a proper format for bug fix, pull requests, new feature addition etc. |
| Title |       Feature request             |
| **Is your feature request related to a problem? Please describe.** | New Contributors are not able to follow a proper format to create issue for bug fixes, pull request,  new feature additions etc. |
| **Describe the solution you'd like**                               | I can provide ".github" folder with all the necessary templates required it will not only help the contributors but mentors as well |
| **Additional context**                                             | I am from GSSOC'23 you can assign this issue to me |

**Comment by abhijeet141** [comment]
Hi @tuhinaww 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by tuhinaww** [comment]
@abhijeet141 thanks a lot for considering me :)

if possible, please add the level tag as well. Looking forward to more contributions!!

**Comment by abhijeet141** [comment]
Sure !
