### ISSUE TITLE
Improving accuracy of model using Decision Tree and SVM algorithm

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [abhijeet141/CropForesight#17]
Hey @abhijeet141 I would like to contribute under GSSOC. 
The accuracy of the ML model can be improved using Decision Tree and SVM algorithm that helps to identify the pattern among data and then process it as per the input conditions.

**Comment by abhijeet141** [comment]
Hi @i-am-SnehaChauhan 
Thank you for creating the issue. However, after careful consideration, I believe that our model's current accuracy of 99% is already quite high and meets our requirements. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
