### ISSUE TITLE
Fixing the FrontEnd

### ISSUE THREAD

**Issue by NisargPipaliya** [abhijeet141/CropForesight#18]
There are few problems in front-end.
Please assign me the issue, I would like to work on that.

@abhijeet141

**Comment by NisargPipaliya** [comment]
![Screenshot (344)](https://github.com/abhijeet141/CropForesight/assets/96529542/1c68ece9-2ff8-43cb-9d7f-b4f6e31ca764)
![Screenshot (345)](https://github.com/abhijeet141/CropForesight/assets/96529542/57bddbb5-03d4-4d19-8ee1-c729e5964ed3)

**Comment by abhijeet141** [comment]
Hi @NisargPipaliya 
Thank you for creating the issue I think it is resolved now check it once
