### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [abhijeet141/CropForesight#2]
I would like to improve the readme file of this project. I would like add the necessary information and make make it more engaging for the user.

**Comment by harshsingh32** [comment]
I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by abhijeet141** [comment]
Hi @harshsingh32 
Thank you for creating the issue. I have reviewed it, and it looks like a great opportunity to contribute. While we don't have a formal assignment process in place at the moment, you can definitely start working on it.

If you have any questions or need any assistance along the way, please don't hesitate to ask.

Thank you for your contribution, and I look forward to seeing your progress on resolving the issue.
