### ISSUE TITLE
Add a footer section

### ISSUE THREAD

**Issue by KhushiTayal** [abhijeet141/CropForesight#20]
Adding a footer section will make the UI look more complete. 

@abhijeet141 Please assign me this issue under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @KhushiTayal 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask the website design is changed so pull all the changes before starting.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by SoundaryaKoutharapu** [comment]
Hey @KhushiTayal Are you still working on this issue.?

**Comment by KhushiTayal** [comment]
Yes I am almost done with the task

**Comment by KhushiTayal** [comment]
@abhijeet141 I have generated the pull request, please check.
