### ISSUE TITLE
[GSSOC'23] Using pytorch to improve model accuracy

### ISSUE THREAD

**Issue by karthikbhandary2** [abhijeet141/CropForesight#22]
I would like to use Pytorch and improve the performance by getting better accuracy.

**Comment by abhijeet141** [comment]
Hi @karthikbhandary2 
Thank you for creating the issue. However, after careful consideration, I believe that our model's current accuracy of 99% is already quite high and meets our requirements. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
