### ISSUE TITLE
Implementing both light mode and dark mode to the website

### ISSUE THREAD

**Issue by Raghucharan16** [abhijeet141/CropForesight#23]
Hey, wanted to change some css and implement a dark mode with a toggle. as many prefer dark mode it'll be user freindly.
assign me on this one under GSSoC label.

**Comment by abhijeet141** [comment]
Hi @Raghucharan16 do you want to add dark mode in the home or form page ?

**Comment by Raghucharan16** [comment]
Hey @abhijeet141 . It would be nice if whole website has an option and also there is spelling mistake: **pridicting** instead of **predicting** in the home page. So assign me for this one I'll modify and let you know. And also add a GSSoC label 😅. Thank you

**Comment by abhijeet141** [comment]
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

**Comment by Raghucharan16** [comment]
Hey @abhijeet141 Can you add the label for the problem as well. Thank you
