### ISSUE TITLE
💡 [REQUEST] - <Working Tkinter GUI for the the ML Model>

### ISSUE THREAD

**Issue by dhruvsaxena11** [abhijeet141/CropForesight#28]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

@abhijeet141 Respected Sir,

I want to add a Tkinter GUI for the project with the ML model for all the predictions and giving the output.
I will make it for to take the manual features input and the backend ML model will compute the results and display it on the GUI.

Plz kindly assign this request to me. It will be a big opportunity for me.

Thank You

Dhruv Saxena
### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @dhruvsaxena11 
This project is already using ReactJs for frontend so I think it does not need a tkinter gui for the prediction. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
