### ISSUE TITLE
💡 [REQUEST] - Adding section-wise 'back-to-top' in ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [abhijeet141/CropForesight#29]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---
 - The ReadMe.md is very informative and so is lengthy.
 - Navigating back to the top can be improved by adding a section-wise 'back-to-top' link .
 - Could this be assigned to me? Thank You.

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @VSatwika 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
