### ISSUE TITLE
💡 [REQUEST] - Modifications in form page

### ISSUE THREAD

**Issue by VSatwika** [abhijeet141/CropForesight#31]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

 - In the form page, because of the background, the labels are not visible. I would like to change their color to a brown shade.
 - The spelling of 'Recommendation' is wrong in the form title.
 - The form title color can also be changes as it is not visible.
 - Could I also add a back to top button in the form page?
 
   Could this issue be assigned to me? @abhijeet141

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @VSatwika 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
