### ISSUE TITLE
💡 [REQUEST] - Add 404 error component

### ISSUE THREAD

**Issue by SINJINI-G** [abhijeet141/CropForesight#32]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |No error message for unknown routes|
| **Solution Proposed**      |I will add a 404 page for unknown routes|
| **Screenshots**            |
![image](https://github.com/abhijeet141/CropForesight/assets/98143022/b07b7a91-b12d-46c9-8521-86030071365f)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @SINJINI-G 
Thank you for creating the issue. A similar issue is already created #11 if there will be no response I will assign this issue to you.

**Comment by SINJINI-G** [comment]
> Hi @SINJINI-G Thank you for creating the issue. A similar issue is already created #11 if there will be no response I will assign this issue to you.

Yeah sure!! Looking forward to contributing in your project.

**Comment by PatilHarshh** [comment]
hi @abhijeet141  can you please assign this 404 Error page to me i have prior experience in this

**Comment by PatilHarshh** [comment]
@SINJINI-G  can we collaborate ?

**Comment by SINJINI-G** [comment]
> @SINJINI-G Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for assigning this to me!!

**Comment by SINJINI-G** [comment]
waiting for your preview.. did a PR https://github.com/abhijeet141/CropForesight-FrontEnd/pull/27 @abhijeet141

**Comment by PatilHarshh** [comment]
@SINJINI-G did you added routing?
