### ISSUE TITLE
Enhancement in Navbar

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#36]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |  Improve the UI of the navbar. |
| **Solution Proposed**      | By adding a hover effect to the navbar section and redesigning it to make it more enhanced.|
| **Additional Context**     |This would improve user experience and engagement - the overall look of the website.|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Hover effect is already added on Navigation if you think you can improve the design more message me I will assign this issue to you.
