### ISSUE TITLE
💡 [REQUEST] - Creating a About Us Section

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#37]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | When we click on About in NavBar, nothing happens, thus I want to create an About Us Section where the user is redirected to while clicking on About  |
| **Solution Proposed**      |This would be quite beneficial as the user will get to know about CropForeSight, its significance etc...|
| **Alternative Solutions**  |We may create a section on the main page for About Us, or a separate page.  |
| **Additional Context**     |It would improve overall user experience and engagement. |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhi03ruchi** [comment]
Resolved Issue #37 , I have created a pull request plz review and merge.
