### ISSUE TITLE
404 Error page

### ISSUE THREAD

**Issue by PatilHarshh** [abhijeet141/CropForesight#38]
I am from GSSoC'23.
I would like to be assigned this task.

I want to add 404 Error page in this project please assign 
![Screenshot (58)](https://github.com/abhijeet141/CropForesight/assets/120102234/237b4c7d-4b12-49a8-9ab8-ab33cadf70ce)
it to me @abhijeet141

**Comment by abhijeet141** [comment]
Hi @PatilHarshh 
Thank you for creating the issue but the similar issue is already assigned. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
