### ISSUE TITLE
🐛 [BUG] - Glitch in Contact Us Page

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#39]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | There is an alignment issue in the Contact Us form, which affects user experience. |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue: https://github.com/abhi03ruchi  |
| **Screenshots** | I want to fix this issue.
<img width="1368" alt="Screenshot 2023-05-25 at 7 34 19 PM" src="https://github.com/abhijeet141/CropForesight/assets/105661636/74b5ef62-423a-4394-8a9b-134a0b23697c">  |
|  |  Plz assign me this task under gssoc'23. |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [ ] Windows
- [ ] Linux
- [x] Mac
- [x] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [x] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by akuldeepj** [comment]
Hey @abhi03ruchi  did you try it in chrome

**Comment by abhijeet141** [comment]
@abhi03ruchi Once clear your browser cache and then check
