### ISSUE TITLE
Adding a blog page to the website.

### ISSUE THREAD

**Issue by Sathvik902** [abhijeet141/CropForesight#4]
I have noticed that, this website has a single page which predicts the crop.
Adding a blog page about different crops and locations in which they can be grown can enhance the website.

@abhijeet141,
I would love to contribute to this issue as a part of @GSSOC'23.
Please assign it to me. Thank you.

**Comment by UditSharma9999** [comment]
I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @Sathvik902,

Thank you for creating the issue. I have reviewed it, and I completely agree that adding a blog page about different crops and their suitable locations would enhance the website. It's an excellent opportunity for you to contribute.

Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhijeet141** [comment]
Hi @UditSharma9999 @sijalalyy @syedawanya18 
Thank you all for showing interest in working on this issue. If there will be no response within a reasonable timeframe, I will assign the issue to each of you, one by one, in the order of your comments.

**Comment by Sathvik902** [comment]
Thank you so much! @abhijeet141

**Comment by Sathvik902** [comment]
I'll do it in 1 days. Thanks.

**Comment by abhijeet141** [comment]
@Sathvik902 Any update ?

**Comment by abhijeet141** [comment]
@UditSharma9999 Are you interested in doing this issue ?

**Comment by UditSharma9999** [comment]
No. Thank you

**Comment by Sathvik902** [comment]
It will be done by tomorrow. Thanks
