### ISSUE TITLE
🐛 [BUG] - <Predict crop page content not visible>

### ISSUE THREAD

**Issue by Sameep002** [abhijeet141/CropForesight#41]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | predict crops page contents are not visible ,I am contributor and will make required changes for better user experience!! |
| **Addition of any** | If any more changes needed let me know! |

**Comment by abhijeet141** [comment]
Hi @Sameep002,
Thank you for creating the issue but the similar issue is already assigned. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.

**Comment by Sameep002** [comment]
Sure, if any will let you know !!
