### ISSUE TITLE
📉 graph

### ISSUE THREAD

**Issue by Anishkagupta004** [abhijeet141/CropForesight#42]
I am from GSSoC'23.

Problem -No 3D visualisation 
Solution-Graph showing percentage of chemicals in 3d model.
Also graph showing humidity,rainfall,etc different parameters percentage.

**Comment by abhijeet141** [comment]
Hi @Anishkagupta04 
Thank you for creating the issue but the similar issue is already assigned. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
