### ISSUE TITLE
Farmers info

### ISSUE THREAD

**Issue by Anishkagupta004** [abhijeet141/CropForesight#43]
- [x] I am from GSSoC'23.
-
In this we can have mini icon of what is related to what topic we can include farmers information 
![Screenshot_20230526_205818](https://github.com/abhijeet141/CropForesight/assets/123764336/eaf19a79-fe89-4eb3-a83e-283d5d1a157d)

**Comment by abhijeet141** [comment]
Hi @Anishkagupta04 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Anishkagupta04** [comment]
I have updated the comment.As i m a beginner require assistance!
