### ISSUE TITLE
💡 [REQUEST] -  Add a pyrhon notebook file and improve the model 

### ISSUE THREAD

**Issue by devatraj** [abhijeet141/CropForesight#44]
- [ ] I am from GSSoC'23.
- [ ] I would like to be assigned this task.
It will be good to create a pipelined model for predictions. Addition of ipynb will make it more readable

**Comment by abhijeet141** [comment]
Hi @devatraj 
Thank you for creating the issue. However, after careful consideration, I believe that our model's current accuracy of 99% is already quite high and meets our requirements. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
