### ISSUE TITLE
UI/UX of the website in figma 

### ISSUE THREAD

**Issue by aasthaaaa7** [abhijeet141/CropForesight#45]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

I would like to design the home page and other pages of the website in figma

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @aasthaaaa7 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
