### ISSUE TITLE
💡Home Page Ui Need Padding

### ISSUE THREAD

**Issue by ayushlohmod** [abhijeet141/CropForesight#46]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---
The home page of the website looks off it needs some padding and some improvement 
Please assign this to me i really want to work on this
### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @ayushlohmod 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
