### ISSUE TITLE
💡 Make the Navbar, About & Contact Us responsive

### ISSUE THREAD

**Issue by mohammadshaad** [abhijeet141/CropForesight#47]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Right now the UI of the navbar is not perfectly responsive and the about page also lacks the responsiveness|
| **Solution Proposed**      |I want to improve the responsiveness of the navbar, about & contact us page UI improvements|
| **Additional Context**     |I will improve the UI as I am a UI UX designer and developer|
| **Screenshots**            |<img width="329" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/89409389/e8e29691-269f-4579-bba8-c2265a6ae83b">|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by mohammadshaad** [comment]
@abhijeet141 kindly assign me this issue

**Comment by abhijeet141** [comment]
Hi @mohammadshaad 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by mohammadshaad** [comment]
Thanks a lot also kindly add the level tag as well

**Comment by abhijeet141** [comment]
@mohammadshaad I will add the level once you will create the PR I will review it and assign the Level
