### ISSUE TITLE
Action upon submitting the Contact Us Form

### ISSUE THREAD

**Issue by somenath203** [abhijeet141/CropForesight#48]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Perform an action when a user successfully submits all the details in the 'Contact Us' form and clicks on the 'Send' button|
| **Solution Proposed**      |Display a Sweetalert modal when the user clicks on the 'send' button saying 'Thanks for contacting us, we have received your details successfully'|
| **Additional Context**     |This would improve overall user experience|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @somenath203 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
