### ISSUE TITLE
Adding more parameters in ML model

### ISSUE THREAD

**Issue by Mansi168** [abhijeet141/CropForesight#5]
hey @abhijeet141 we can add more parameters in the ml model such as 
soil type- including this parameter can help tailor recommendations based on the specific soil characteristics of the land; 

Organic Matter Content-the organic matter content of soil is an important factor for crop productivity. It affects soil fertility, water holding capacity, and nutrient availability. Incorporating this parameter can provide more accurate recommendations.

I would like to work upon these!!

**Comment by UditSharma9999** [comment]
I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by abhijeet141** [comment]
Hi @Mansi168 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Mansi168** [comment]
thanks @UditSharma9999 :)

**Comment by Mansi168** [comment]
Thanks @abhijeet141 :)

**Comment by parridhi** [comment]
### Hey! @abhijeet141!
#### I want to work on this issue under GSSoC'23. I have previously worked on Machine Learning models for various prediction projects and would thus like to work on this. 
#### Kindly assign this issue to me.
