### ISSUE TITLE
Can I place the predict your crop at the right position 

### ISSUE THREAD

**Issue by hardiksharma02** [abhijeet141/CropForesight#50]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Write a concise and appropriate description of the feature request |
| **Solution Proposed**      |Describe the solution you would want|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ ] I follow the Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @hardiksharma02 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
