### ISSUE TITLE
💡 [REQUEST] - Making codes of readme.md as  code-text in readme.md [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#52]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The readme file has some codes in the local development section, but that code is in text format which makes it difficult to understand and also difficult to copy.|
| **Solution Proposed**      |I have already edited the readme file on my fork, Once I am assigned this issue I will make the pull request.|
| **Alternative Solutions**  |Nope|
| **Additional Context**     |Please Assign me under GSSoC'23|
| **Screenshots**            

Before:
![beforell](https://github.com/abhijeet141/CropForesight/assets/116020663/e0ceb10d-34c8-45d6-82f2-fa68bb881cfa)

After: 
![after](https://github.com/abhijeet141/CropForesight/assets/116020663/305642d1-8e07-4b93-a3d3-33c7b3099cf8)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @1Shubham7 
Thank you for creating the issue but form next time please create PR only when your issue has been assigned.

**Comment by 1Shubham7** [comment]
@abhijeet141 Thank you so much for merging. I will make sure I will only create PR after being assigned an issue.
