### ISSUE TITLE
Adjust content at about page 💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by Mridul-2003** [abhijeet141/CropForesight#54]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this 

The content at about page in mobile view not correctly adjusted and image is overlapping the font and font size is also large .
| **Screenshots**            |[Provide screenshots here]|
![Screenshot_20230529-110128_Chrome](https://github.com/abhijeet141/CropForesight/assets/110475111/c5d655a2-2748-49be-aa67-d68332fa06ea)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @Mridul-2003 
Thank you for creating the issue but this issue is already assigned
