### ISSUE TITLE
💡 [REQUEST] - Improve the UI of the Home page

### ISSUE THREAD

**Issue by Prakriti2003** [abhijeet141/CropForesight#55]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The home page has a problem with the box displaying the crop prediction, the text is overflowing.| 
| **Solution Proposed**      |I can improve the UI of the home page to make it more attractive and also responsive for all screen sizes.|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |On smaller  screen text and  the positioning of the box and the video is not very attractive & responsive. |
| **Screenshots**            |
![crop](https://github.com/abhijeet141/CropForesight/assets/96686092/0eef0c60-7589-4cc7-a043-e79a085ebefc)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AnishSingh5665** [comment]
I like to contribute on this under GSSOC

**Comment by abhijeet141** [comment]
Hi @Prakriti2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
