### ISSUE TITLE
💡 [REQUEST] - Making the about and predicting page bilingual 

### ISSUE THREAD

**Issue by Prakriti2003** [abhijeet141/CropForesight#56]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Currently the pages are only in english but they should be available in hindi  to reach more people|
| **Solution Proposed**      |I can make the pages in hindi as well and give a translate option to switch languages.|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |A website for farmers if available in hindi will reach more people and be more user friendly.|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @Prakriti2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue. This will be very useful feature.
