### ISSUE TITLE
💡 [REQUEST] - Contact-Us Form Revamp 

### ISSUE THREAD

**Issue by kartikkc** [abhijeet141/CropForesight#58]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The contact us form can be revamped and made more appealing with the design |
| **Solution Proposed**      |Contact Us form and the links to the social media will be placed with the contact us form in a uniform manner|
| **Alternative Solutions**  | Recreating the contact us page | 
| **Additional Context**     |It will improve the chances of getting messages to the mail|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @kartikkc 
Thank you for creating the issue but this issue is already assigned #47 After completion of the task if you think you can make it more appealing then just message me I will assign you.
