### ISSUE TITLE
🐛 [BUG] - Navbar not properly aligned

### ISSUE THREAD

**Issue by rishuraj1** [abhijeet141/CropForesight#59]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Currently navbar is not properly aligned. (i.e., the logo and the home, about, contact should have enough space in between them. It does not look good and appealing now.) |
| **Screenshots** | current: <img width="957" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/47839626/c12854e8-febe-4eb1-9035-a1c25d5957a5">  proposed change:  <img width="960" alt="Screenshot 2023-05-30 160508" src="https://github.com/abhijeet141/CropForesight/assets/47839626/65baac29-aa98-4356-9e9e-88695fad981e"> |
| **Additional Context** | I would love to contribute to this project and fix this issue under GSSoC '23 |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Microsoft Edge
- [ ] Opera
- [x] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [x] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @rishuraj1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
