### ISSUE TITLE
💡 [REQUEST] - not aligned Contact page

### ISSUE THREAD

**Issue by rimi0602** [abhijeet141/CropForesight#61]
- [1 ] I am from GSSoC'23.
- [2 ] I would like to be assigned this task.
---
I'd like to work on the mis-alignment of the contact web page and improve the Ui/Ux. @abhijeet141 
<img width="960" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/110307938/4165b0f3-aecc-4f42-a85a-c736cca4d9e2">

### Code of Conduc

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @rimi0602 
Thank you for creating the issue but this issue is already assigned #47
