### ISSUE TITLE
💡 [REQUEST] - Blog Section Addition

### ISSUE THREAD

**Issue by rimi0602** [abhijeet141/CropForesight#62]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---
Addition of Blog section in the website can help them learn about how to efficiently grow crops that they got after prediction. It'll act like a dictionary of crops and how to grow them.
@abhijeet141 

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @rimi0602 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhi03ruchi** [comment]
I would like to work on the issue , plz assign it to me under gssoc'23.
