### ISSUE TITLE
🐛 [BUG] - The contact form's field are overflowing (improperly aligned). [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#65]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The contact form's field are overflowing (improperly aligned). |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. Go to home page <br>2. go to contact us.<br>3. You can see the contact form |
**Screenshots** 
![ssgap](https://github.com/abhijeet141/CropForesight/assets/116020663/193416eb-2e24-4ded-b45b-26b9aac15018)
Look at the difference between the gaps. It start to overflow once you see it on small screens

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by 1Shubham7** [comment]
Please assign me this issue.

**Comment by abhijeet141** [comment]
Hi @1Shubham7 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by 1Shubham7** [comment]
Thank you @abhijeet141 . I will surely not disappoint you.

**Comment by 1Shubham7** [comment]
@abhijeet141 There is a mistake. I just solved the issue and realized the PR I will make will be in Corpforsight Forntend, While the issue is in Corpforesight Repo. Can you please assign me the issue there and close it here? Please do it as soon as you can. I have completed the PR I just have to merge it.

**Comment by abhijeet141** [comment]
@1Shubham7 It does not matters your progress will be tracked based on the labels on PR.

**Comment by 1Shubham7** [comment]
@abhijeet141 But how can I make a PR here if code is from CropForesight Frontend. Please reply soon, I will be eagarly waiting. I have even created an issue there.

**Comment by abhijeet141** [comment]
@1Shubham7 You don't have to make a PR here you have to make PR on CropForesight Frontend part only

**Comment by 1Shubham7** [comment]
ok @abhijeet141 . Thank you.

**Comment by 1Shubham7** [comment]
@abhijeet141 https://github.com/abhijeet141/CropForesight-FrontEnd/pull/68 here is the link to PR. Please merge it and close this issue. This issue was such an headache.
