### ISSUE TITLE
💡 [REQUEST] - Adding Scroll to top Button

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#67]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |i would like to add scroll to top button(with a slight animation effect ) for the website. This would enhance user experience and engagement.  |
| **Screenshots**            | Sample(will modify based UI of website) : <img width="87" alt="Screenshot 2023-06-04 at 3 38 50 PM" src="https://github.com/abhijeet141/CropForesight/assets/105661636/26f1aeed-e8f2-48d4-9990-203a73cef51b">  |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhi03ruchi** [comment]
Resolved Issue #67 , plz review and merge.
