### ISSUE TITLE
🐛 [BUG] - Adding Back to Home Icon the Crop Recommendation Page.

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#68]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Please provide a clear and concise description of the bug |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. Step 1...<br>2. Step 2...<br>3. Step 3...<br>4. Step 4... |
| **Screenshots** | ![Screenshot 1](screenshot1.png) |
| **Logs** | Relevant log output goes here |
| **Additional Context** | Please provide any other relevant information about the problem |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [ ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [ ] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [ ] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [ ] I follow Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
This Issue is already assigned and the PR is generated but there are some conflicts so I have not merged it so I am closing this issue.
