### ISSUE TITLE
💡 [REQUEST] - Testimonial Page

### ISSUE THREAD

**Issue by Deepanshu0703** [abhijeet141/CropForesight#69]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |It would make a great impact if you add some testimonials |
| **Solution Proposed**      |I want to add our testimonial page |
| **Additional Context**     | |
| **Screenshots**            | Just an Example
![image](https://github.com/abhijeet141/CropForesight/assets/114489502/b313e7b0-353f-413f-8e82-21d032055bfa)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @Deepanshu0703 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
