### ISSUE TITLE
Output : Rice , then Rice Pic shown {Similarly with other crops}

### ISSUE THREAD

**Issue by thestarsahil** [abhijeet141/CropForesight#7]
![1](https://github.com/abhijeet141/CropForesight/assets/84167034/b00bde68-9996-439b-b626-4f939da865a6)
![2](https://github.com/abhijeet141/CropForesight/assets/84167034/40916a04-c339-4eee-96a2-851efd3dc351)
![3](https://github.com/abhijeet141/CropForesight/assets/84167034/9b8f0aab-f9d2-4c6e-854e-015c09704565)

This will look like this

**Comment by Singh-Vibhor** [comment]
I would like to contribute to this under GSSOC'23.

**Comment by abhijeet141** [comment]
Hi @thestarsahil 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by AnishSingh5665** [comment]
I would like to contribute to this under GSSOC23

**Comment by Mridul-2003** [comment]
Plz assign me this task..
