### ISSUE TITLE
🐛 [BUG] - The Typography box is flickering and resizing itself on typing animation

### ISSUE THREAD

**Issue by arin-paliwal** [abhijeet141/CropForesight#70]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The Typography box is flickering and resizing itself on typing animation in the home page |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. Open the home page of the application<br>2. Observe the Typography box with typing animation<br>3. Notice the flickering and resizing behavior |
| **Screenshots** | ![image](https://github.com/abhijeet141/CropForesight/assets/100232893/67101c62-23f4-4250-8f32-0f817e2d8652)|

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Microsoft Edge
- [x] Opera
- [x] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [x] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [x] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [x] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [x] High
- [ ] Medium
- [ ] Low

## Assign it to me, I have the updated code I have fixed the issue

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @arin-paliwal 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by arin-paliwal** [comment]
> Hi @arin-paliwal Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.
> 
> Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

Sure,
I had fixed the issue and now I am creating a PR for that
