### ISSUE TITLE
🐛 [BUG] - Error on Frontend page[GSSOC'23]

### ISSUE THREAD

**Issue by smty2018** [abhijeet141/CropForesight#71]
## 🐛 Bug Report Form 

|                |                     |
|----------------|---------------------|
| **Description** | Spelling Error in Frontend Page |
| **Reproduction URL** | https://github.com/smty2018 |
| **Reproduction Steps** | 1. Step 1...<br>2. Step 2...<br>3. Step 3...<br>4. Step 4... |
| **Screenshots** | ![Screenshot 1](screenshot1.png) |
| **Logs** | Relevant log output goes here |
| **Additional Context** | Please provide any other relevant information about the problem |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [ ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [ ] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [ ] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [ ] I follow Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme.

**Comment by smty2018** [comment]
@abhijeet141 Please assign me this issue

**Comment by abhijeet141** [comment]
Hi @smty2018 
Thank you for creating the issue but this issue is already created https://github.com/abhijeet141/CropForesight-FrontEnd/issues/36
