### ISSUE TITLE
💡 [REQUEST] - Adding info/(link to some website) and a photo of the crop that is recommended.

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#72]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | When any crop is recommended, we can add the photo of the crop and either some Info or some more   |
| **Solution Proposed**      | adding a photo of the crop and either some info or a link to some informative website |
| **Alternative Solutions**  | Above solution is the best solution |
| **Additional Context**     |Please assign me this issue under GSSoC'23|
| **Screenshots**            | 
![cropcard](https://github.com/abhijeet141/CropForesight/assets/116020663/1445a283-018c-432b-b129-65add8961c50)
 |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by abhijeet141** [comment]
Hi @1Shubham7 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by 1Shubham7** [comment]
Thank you @abhijeet141 . I will surely not disappoint you.
