### ISSUE TITLE
💡 [REQUEST] - Adding Contributor List in readme

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#74]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | I would like to add a contributor list to the readme.  |
| **Solution Proposed**      | Adding a contributor list would enhance the readme and encourage more individuals to contribute.    |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
