### ISSUE TITLE
💡 [REQUEST] - Improve README.md

### ISSUE THREAD

**Issue by roberanegussie** [abhijeet141/CropForesight#76]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |In the **Clone Frontend and Backend Repository** section the username is of the repository owner  |
| **Solution Proposed**      |It is better to replace that with _your_username_|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**               |
![image](https://github.com/abhijeet141/CropForesight/assets/47657043/6f7784bc-086e-4919-a94d-e01759225e3f)
![image](https://github.com/abhijeet141/CropForesight/assets/47657043/89f54f53-26b3-4525-bbf4-b15757c06712)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @roberanegussie 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
