### ISSUE TITLE
💡 [REQUEST] - Change the background image/ or the font color as it is not visible properly

### ISSUE THREAD

**Issue by smty2018** [abhijeet141/CropForesight#79]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Not visible properly |
| **Solution Proposed**      |Change the background image/ or the font color as it is not visible properly|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**       |     
![image](https://github.com/abhijeet141/CropForesight/assets/74114936/8c1ea418-f20d-45cf-ad57-8edb1c86429b)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by smty2018** [comment]
@abhijeet141 please assign me this issue under gssoc'23

**Comment by abhijeet141** [comment]
@smty2018 Thank you for creating this issue but the issue is already resolved.
