### ISSUE TITLE
🐛 [BUG] - The heading in the Predict Crop Form not visible properly

### ISSUE THREAD

**Issue by laxanarana1513** [abhijeet141/CropForesight#81]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The heading in the Crop Predict page is not properly visible |
| **Reproduction URL** | https://github.com/laxanarana1513 |
| **Reproduction Steps** | 1. Step 1...<br>2. Step 2...<br>3. Step 3...<br>4. Step 4... |
| **Screenshots** | ![Screenshot (38)](https://github.com/abhijeet141/CropForesight/assets/71834515/02a5d27f-d157-48e4-a1e2-0b229a7b680a) |
| **Logs** | Relevant log output goes here |
| **Additional Context** | Please provide any other relevant information about the problem |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [x] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by laxanarana1513** [comment]
I am under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @laxanarana1513 
Thank you for creating the issue but this issue is already resolved.
