### ISSUE TITLE
🐛 [BUG] - Contact Us Page Jumbled

### ISSUE THREAD

**Issue by kaashikaagrawal** [abhijeet141/CropForesight#83]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| The current contact us page form is all jumbled with the text boxes not aligned correctly as well as the text not visible. |

| **Screenshots** | 
<img width="944" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/97745349/96b4cf46-0ed8-44f6-8887-72a36ca45400">
|

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [o ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [o ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

🔍 **Priority**
Please select the priority of the bug:
- [ o] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [o ] I follow Contributing Guidelines of this project.
- [o ] I have checked the current issues for duplicate problems.
- [ o] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @kaashikaagrawal 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by kaashikaagrawal** [comment]
@abhijeet141 there is no package.json file nor is there a cropforesight-frontend folder after forking. How can i run this project?
