### ISSUE TITLE
🐛 [BUG] - Weather Page slight revamp

### ISSUE THREAD

**Issue by kaashikaagrawal** [abhijeet141/CropForesight#84]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The weather page is too blank and also has a spelling mistake. (Loaction instead of Location) |

| **Screenshots** | <img width="960" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/97745349/94db957a-1881-40bf-bd5d-28dd12123aee">|

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [. ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [. ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

🔍 **Priority**
Please select the priority of the bug:
- [ .] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [. ] I follow Contributing Guidelines of this project.
- [ .] I have checked the current issues for duplicate problems.
- [. ] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @kaashikaagrawal 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by kaashikaagrawal** [comment]
@abhijeet141  there is no package.json file nor is there a cropforesight-frontend folder after forking. How can i run this project?

**Comment by abhijeet141** [comment]
@kaashikaagrawal 
Just follow these steps -  
Clone the frontend repository:

git clone https://github.com/your_username/CropForesight-FrontEnd.git

Change to the project directory:

cd CropForesight-FrontEnd

Install the required dependencies:

npm install

Run the frontend:

npm start

**Comment by kaashikaagrawal** [comment]
@abhijeet141 
cd CropForesight-FrontEnd does not work as there is no folder named CropForesight-FrontEnd
<img width="453" alt="image" src="https://github.com/abhijeet141/CropForesight/assets/97745349/80f22189-7f09-4e70-80d1-f52fe3591606">

**Comment by kaashikaagrawal** [comment]
@abhijeet141 have finished working on this issue and created a pull request in the CropForesight-FrontEnd repository. Please review and let me know if the PR can be merged.
