### ISSUE TITLE
🐛 [BUG] - <Site is not fully responsive>

### ISSUE THREAD

**Issue by SubhamB2003** [abhijeet141/CropForesight#86]
## 🐛 Bug Report Form

This site is not fully responsive there is many conflict component. You can see below

Hey, I am willing to contribute to this issue.
Please assign it to me under the GSSOC'23. 

![image](https://github.com/abhijeet141/CropForesight/assets/94003231/2692e7ad-5436-4c2b-b36f-1da4a4ca830b)

![image](https://github.com/abhijeet141/CropForesight/assets/94003231/4dbb902f-d03b-4482-a3cd-115e608d1d7d)

![image](https://github.com/abhijeet141/CropForesight/assets/94003231/24133173-7300-4696-bbbd-7031bbee41af)

![image](https://github.com/abhijeet141/CropForesight/assets/94003231/3611db94-ae36-44e5-84dd-72597a91bf58)

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [ ] I follow Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @SubhamB2003 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by SubhamB2003** [comment]
> Hi @SubhamB2003 Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.
> 
> Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

Hey, can I open a new issue in your "CropForesight-Frontend" repo bcz otherwise I am not able to tag which issue I solved?
