### ISSUE TITLE
🐛 [BUG] -  Optimising the Code

### ISSUE THREAD

**Issue by abhi03ruchi** [abhijeet141/CropForesight#88]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Presently, each page has a separate nav component  |
| **Screenshots** | [Screenshot 1] <img width="793" alt="Screenshot 2023-06-14 at 11 10 12 PM" src="https://github.com/abhijeet141/CropForesight/assets/105661636/b5ae4dc7-f86d-4027-a442-1fcc5362c993"> |
| **Additional Context** | Each page about, contact, home etc has such a section. I want to optimise the code and create a navbar.jsx and then add </NAVBAR> to each page. This will avoid the repetition of the same code again and again on all the pages. 

This will enhance the code and help contributors better understand and enhance their contributing experience. 
Plz assign me this task under gssoc'23.

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [ ] Windows
- [ ] Linux
- [x] Mac
- [x] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [x] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @abhi03ruchi 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
