### ISSUE TITLE
💡 [REQUEST] - Designing and coding a footer to the homepage with Figma + ReactJS [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [abhijeet141/CropForesight#89]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The homepage of the website will look significantly better upon adding a footer |
| **Solution Proposed**      | I can design a footer with figma and code it |
| **Alternative Solutions**  | None |
| **Additional Context**     | Please assign me this issue under GSSoC'23 |
| **Screenshots**            

![FOOTER@](https://github.com/abhijeet141/CropForesight/assets/116020663/4c820277-baba-4573-a26d-6e865bf221e9)

![FOOTER3](https://github.com/abhijeet141/CropForesight/assets/116020663/71321cd5-cdc1-430d-87ad-fb45bd9245e7)

![FOOTER 4](https://github.com/abhijeet141/CropForesight/assets/116020663/c8ff7f48-9028-48bd-baf5-cb9a68c27775)

![FOOTER](https://github.com/abhijeet141/CropForesight/assets/116020663/f5f0cdbc-23e6-4721-972b-521186e4cd91)
 

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by abhijeet141** [comment]
Hi @1Shubham7 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by abhijeet141** [comment]
@1Shubham7 The same issue was already created and i missed that https://github.com/abhijeet141/CropForesight-FrontEnd/issues/66 Wait for someday if there will be no response than you can start working on this issue.

**Comment by 1Shubham7** [comment]
ok
