### ISSUE TITLE
Improving accuracy by adding DL algorithms

### ISSUE THREAD

**Issue by Rhythm408** [abhijeet141/CropForesight#9]

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by abhijeet141** [comment]
Hi @sijalalyy 
Thank you for creating the issue. However, after careful consideration, I believe that our model's current accuracy of 99% is already quite high and meets our requirements. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.

**Comment by Rhythm408** [comment]
Thank you for your response.
