### ISSUE TITLE
💡 [REQUEST] - Go Back Button

### ISSUE THREAD

**Issue by parthpathakpp1** [abhijeet141/CropForesight#90]
- [x] am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |There is no button on the form page to return to the main page.|
| **Solution Proposed**      |I will add a button on the form page when the button is clicked the user will return to the main page again 
| **Screenshots**            |

https://github.com/abhijeet141/CropForesight/assets/85991449/aaf40319-595e-40c1-9d96-243d40649656

|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @parthpathakpp1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
