### ISSUE TITLE
💡 [REQUEST] - Contact Page

### ISSUE THREAD

**Issue by parthpathakpp1** [abhijeet141/CropForesight#91]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Everything on Contact Page is misaligned that does not look good. |
| **Solution Proposed**      |I will fix all the problems on the contact page.|
| **Screenshots**            |
![foresightissue2](https://github.com/abhijeet141/CropForesight/assets/85991449/aff973d9-8947-4567-a26c-2626a9856bdd)
|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @parthpathakpp1 
Thank you for creating the issue but this issue is already present #83
