### ISSUE TITLE
💡 [REQUEST] - About Page

### ISSUE THREAD

**Issue by parthpathakpp1** [abhijeet141/CropForesight#92]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |About Us page needs improvement in it. There are a lot of things to be fixed. |
| **Solution Proposed**      |I will improve the About Us Page.  |
| **Screenshots**            |

https://github.com/abhijeet141/CropForesight/assets/85991449/1e765c88-11c8-4806-8c1a-07f4fb9037ca

|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @parthpathakpp1 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
