### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [abhijeet141/CropForesight#94]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@abhijeet141 please assign me this issue under gssoc'23.

**Comment by abhijeet141** [comment]
Hi @Anshika-Jain02 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
