### ISSUE TITLE
🐛 [BUG] - <Grammatical Mistake>

### ISSUE THREAD

**Issue by dheeraj1129** [abhijeet141/CropForesight#96]
The grammatical mistake in (Crop Recomendation title ) it should be Crop Recommendation I think so. 

![Screenshot (23)](https://github.com/abhijeet141/CropForesight/assets/72201773/61b566a8-02e1-4c6e-806a-f143bd39f544)

**Comment by abhijeet141** [comment]
Hi @dheeraj1129 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
