### ISSUE TITLE
💡 [style]: Text is not visible 

### ISSUE THREAD

**Issue by dheeraj1129** [abhijeet141/CropForesight#97]
The text is not visible because of the white blur background color which decreases the visiblirty of text in a small device
![Screenshot (25)](https://github.com/abhijeet141/CropForesight/assets/72201773/d98a9bc6-68f5-4bae-b53e-23a8fb8f9686)

**Comment by abhijeet141** [comment]
Hi @dheeraj1129 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by dheeraj1129** [comment]
hi, @abhijeet141 I am a beginner in open source contribution, but as I can see, no HTML, CSS, JAVASCRIPT, or REACT files are present. Please tell me how I can run this project, I am struggling with this problem.
