### ISSUE TITLE
💡 [Feature] - Error Message

### ISSUE THREAD

**Issue by Vanoita** [abhijeet141/CropForesight#98]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The website lacks an error message feature that notifies users when they enter incorrect location details|
| **Solution Proposed**      |Show an error message when the user enters wrong location details |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by abhijeet141** [comment]
Hi @Vanoita 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Vanoita** [comment]
Hello!
I have made a pull request (PR) in the CropForesight-Frontend repository. Can you please review the changes I made?.
