### ISSUE TITLE
🐛 [BUG] - Change the units of temperature displayed

### ISSUE THREAD

**Issue by Vanoita** [abhijeet141/CropForesight#99]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | When we input the location in the search bar on the weather tab, the temperature displayed is in Kelvin, which is not a metric scale. I would like to change the units to Celcius. |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [ ] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [x] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by abhijeet141** [comment]
Hi @Vanoita 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.

**Comment by Vanoita** [comment]
Hello!
I have made a pull request (PR) in the CropForesight-Frontend repository. Can you please review the changes I made?
